### ISSUE TITLE
Module name not comply with composer 2.0

### ISSUE THREAD

**Issue by Wohlie** [PAYONE-GmbH/magento-2-simple-protect#6]
Hi, I get the following composer deprecation warning:
`Deprecation warning: require.payone-gmbh/magento-2-simpleProtect is invalid, it should not contain uppercase characters. Please use payone-gmbh/magento-2-simpleprotect instead. Make sure you fix this as Composer 2.0 will error.`

My current composer version:
`Composer version 1.9.2 2020-01-14 16:30:31`

**Comment by fjbender** [comment]
Thanks for the hint!
